apiVersion: v1
data:
  nginx.conf: |-
    server {
        listen 80;

        location /images/ {
            alias /images/;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.imageServer.name }}
