apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}
                port:
                  number: {{ .Values.frontend.port }} 
    - host: images.{{ .Values.address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.imageServer.name }}
                port:
                  number: {{ .Values.imageServer.port }}
    - host: api.{{ .Values.address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}
                port:
                  number: {{ .Values.backend.port }}
    - host: auth.{{ .Values.address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.auth.name }}
                port:
                  number: {{ .Values.auth.port }}
    - host: cms.{{ .Values.address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.cms.name }}
                port:
                  number: {{ .Values.cms.port }}