apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.database.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.auth.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.database.name }}
    spec:
      volumes:
        - name: {{ .Values.auth.database.name }}
          hostPath:
            path: /data/{{ .Values.auth.database.name }}
      terminationGracePeriodSeconds: 1
      containers:
        - name: {{ .Values.auth.database.name }}
          image: postgres:16
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.auth.database.name }}
          ports:
            - containerPort: {{ .Values.auth.database.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.auth.database.connection.db }}
            - name: POSTGRES_USER
              value: {{ .Values.auth.database.connection.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.auth.database.connection.password }}
            - name: POSTGRES_INITDB_ARGS
              value: --auth=scram-sha-256