apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cms.database.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cms.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cms.database.name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.cms.database.image }}
          ports:
            - containerPort: {{ .Values.cms.database.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.cms.database.connection.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.cms.database.connection.password }}
            - name: POSTGRES_DB
              value: {{ .Values.cms.database.connection.db }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /data/{{ .Values.cms.name }}/database
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cms.database.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cms.database.port }}
      targetPort: {{ .Values.cms.database.port }}
  selector:
    app: {{ .Values.cms.database.name }}
